### ISSUE TITLE
Define enemyPlayer AI

### ISSUE THREAD

**Issue by aharmsen** [PhelanHarris/untrusted#5]
Move all enemyplayer objects up and down independent of the player movement.
Make sure they hit the wall and return based on some sort of timing sequence

**Comment by g1-DT** [comment]
Generated random directions to move enemy players on the y-coordinates only.  If enemy players are at the boundaries, their directions change.

**Comment by aharmsen** [comment]
Added onCollision functionality so that the Player dies when it comes into contact with the enemyPlayer objects.

**Comment by g1-DT** [comment]
Implementation is completed.
