### ISSUE TITLE
movePlayer function

### ISSUE THREAD

**Issue by g1-DT** [PhelanHarris/untrusted#8]
1) move ball accordingly
    1a) move ball if pushing into space occupied by ball
    1b) kick ball if function phone activated and you are beside ball
2) look for interaction with players
3) stop at the invisible wall

**Comment by aharmsen** [comment]
ball is now pushable

**Comment by aharmsen** [comment]
player is killed if comes into contact with other enemyPlayers, implemented through onCollision properties of the enemyPlayers

**Comment by aharmsen** [comment]
invisibleWall object implemented and made impassible for only the Player object
